# Generated by Django 4.0.6 on 2022-07-15 17:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('changes_date', models.DateField(auto_now=True, null=True)),
                ('photo', models.FilePathField(null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('changes_date', models.DateField(auto_now=True, null=True)),
                ('photo', models.FilePathField(null=True)),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ObjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.category')),
                ('object', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.object')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('changes_date', models.DateField(auto_now=True, null=True)),
                ('photo', models.FilePathField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('creation_date', models.DateField(auto_now_add=True, null=True)),
                ('changes_date', models.DateField(auto_now=True, null=True)),
                ('photo', models.FilePathField(null=True)),
                ('house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.house')),
            ],
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
        migrations.AddField(
            model_name='place',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.room'),
        ),
        migrations.AddField(
            model_name='object',
            name='category',
            field=models.ManyToManyField(through='myapi.ObjectCategory', to='myapi.category'),
        ),
        migrations.AddField(
            model_name='object',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapi.place'),
        ),
    ]
